export const teachersData = [
  {
    id: 1,
    name: "Rajesh Kumar",
    age: 30,
    education: "Masters in Mathematics",
    expertise: ["Mathematics", "Statistics"],
    charge: "₹1500/hour",
    location: "Mumbai, Maharashtra",
    image: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    id: 2,
    name: "Anjali Singh",
    age: 32,
    education: "Bachelor of Science in Physics",
    expertise: ["Physics", "Chemistry"],
    charge: "₹1200/hour",
    location: "New Delhi, Delhi",
    image: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    id: 3,
    name: "Amit Sharma",
    age: 35,
    education: "Ph.D. in History",
    expertise: ["History", "Political Science"],
    charge: "₹1800/hour",
    location: "Bangalore, Karnataka",
    image: "https://randomuser.me/api/portraits/men/3.jpg",
  },
  {
    id: 4,
    name: "Priya Patel",
    age: 28,
    education: "Bachelor of Arts in English Literature",
    expertise: ["English Literature", "Language Arts"],
    charge: "₹1000/hour",
    location: "Ahmedabad, Gujarat",
    image: "https://randomuser.me/api/portraits/women/4.jpg",
  },
  {
    id: 5,
    name: "Sandeep Singh",
    age: 31,
    education: "Masters in Computer Science",
    expertise: ["Computer Science", "Programming"],
    charge: "₹1600/hour",
    location: "Pune, Maharashtra",
    image: "https://randomuser.me/api/portraits/men/5.jpg",
  },
  {
    id: 6,
    name: "Deepika Reddy",
    age: 29,
    education: "Bachelor of Science in Biology",
    expertise: ["Biology", "Environmental Science"],
    charge: "₹1100/hour",
    location: "Hyderabad, Telangana",
    image: "https://randomuser.me/api/portraits/women/6.jpg",
  },
  {
    id: 7,
    name: "Vivek Verma",
    age: 34,
    education: "Ph.D. in Economics",
    expertise: ["Economics", "Business Studies"],
    charge: "₹1900/hour",
    location: "Chennai, Tamil Nadu",
    image: "https://randomuser.me/api/portraits/men/7.jpg",
  },
  {
    id: 8,
    name: "Neha Gupta",
    age: 27,
    education: "Bachelor of Arts in Psychology",
    expertise: ["Psychology", "Sociology"],
    charge: "₹1300/hour",
    location: "Jaipur, Rajasthan",
    image: "https://randomuser.me/api/portraits/women/8.jpg",
  },
  {
    id: 9,
    name: "Rahul Kumar",
    age: 33,
    education: "Masters in Chemistry",
    expertise: ["Chemistry", "Organic Chemistry"],
    charge: "₹1700/hour",
    location: "Kolkata, West Bengal",
    image: "https://randomuser.me/api/portraits/men/9.jpg",
  },
  {
    id: 10,
    name: "Pooja Sharma",
    age: 26,
    education: "Bachelor of Education",
    expertise: ["Primary Education", "Early Childhood Development"],
    charge: "₹900/hour",
    location: "Lucknow, Uttar Pradesh",
    image: "https://randomuser.me/api/portraits/women/10.jpg",
  },
  {
    id: 11,
    name: "Sanjay Singh",
    age: 36,
    education: "Ph.D. in Physics",
    expertise: ["Physics", "Astrophysics"],
    charge: "₹2000/hour",
    location: "Bengaluru, Karnataka",
    image: "https://randomuser.me/api/portraits/men/11.jpg",
  },
  {
    id: 12,
    name: "Meera Desai",
    age: 30,
    education: "Masters in Arts",
    expertise: ["History", "Geography"],
    charge: "₹1400/hour",
    location: "Ahmedabad, Gujarat",
    image: "https://randomuser.me/api/portraits/women/12.jpg",
  },
  {
    id: 13,
    name: "Gaurav Kapoor",
    age: 29,
    education: "Bachelor of Technology in Mechanical Engineering",
    expertise: ["Mechanical Engineering", "Thermodynamics"],
    charge: "₹1500/hour",
    location: "Chandigarh, Punjab",
    image: "https://randomuser.me/api/portraits/men/13.jpg",
  },
  {
    id: 14,
    name: "Shikha Reddy",
    age: 32,
    education: "Masters in Fine Arts",
    expertise: ["Fine Arts", "Painting"],
    charge: "₹1200/hour",
    location: "Hyderabad, Telangana",
    image: "https://randomuser.me/api/portraits/women/14.jpg",
  },
  {
    id: 15,
    name: "Alok Sharma",
    age: 33,
    education: "Ph.D. in Mathematics",
    expertise: ["Mathematics", "Algebra"],
    charge: "₹1800/hour",
    location: "Pune, Maharashtra",
    image: "https://randomuser.me/api/portraits/men/15.jpg",
  },
  {
    id: 16,
    name: "Nisha Patel",
    age: 31,
    education: "Bachelor of Science in Biology",
    expertise: ["Biology", "Anatomy"],
    charge: "₹1300/hour",
    location: "Ahmedabad, Gujarat",
    image: "https://randomuser.me/api/portraits/women/16.jpg",
  },
  {
    id: 17,
    name: "Rajesh Verma",
    age: 34,
    education: "Masters in English Literature",
    expertise: ["English Literature", "Language Arts"],
    charge: "₹1600/hour",
    location: "Kolkata, West Bengal",
    image: "https://randomuser.me/api/portraits/men/17.jpg",
  },
  {
    id: 18,
    name: "Sneha Kapoor",
    age: 27,
    education: "Bachelor of Arts in Sociology",
    expertise: ["Sociology", "Social Work"],
    charge: "₹1100/hour",
    location: "Chennai, Tamil Nadu",
    image: "https://randomuser.me/api/portraits/women/18.jpg",
  },
  {
    id: 19,
    name: "Prashant Mishra",
    age: 35,
    education: "Ph.D. in History",
    expertise: ["History", "Political Science"],
    charge: "₹1900/hour",
    location: "Bengaluru, Karnataka",
    image: "https://randomuser.me/api/portraits/men/19.jpg",
  },
  {
    id: 20,
    name: "Shruti Sharma",
    age: 28,
    education: "Bachelor of Science in Chemistry",
    expertise: ["Chemistry", "Organic Chemistry"],
    charge: "₹1400/hour",
    location: "New Delhi, Delhi",
    image: "https://randomuser.me/api/portraits/women/20.jpg",
  },
  {
    id: 21,
    name: "Rahul Khanna",
    age: 29,
    education: "Masters in Business Administration",
    expertise: ["Business Studies", "Marketing"],
    charge: "₹1500/hour",
    location: "Mumbai, Maharashtra",
    image: "https://randomuser.me/api/portraits/men/21.jpg",
  },
  {
    id: 22,
    name: "Kavita Gupta",
    age: 30,
    education: "Bachelor of Arts in Psychology",
    expertise: ["Psychology", "Counseling"],
    charge: "₹1200/hour",
    location: "Jaipur, Rajasthan",
    image: "https://randomuser.me/api/portraits/women/22.jpg",
  },
  {
    id: 23,
    name: "Vikram Singh",
    age: 32,
    education: "Masters in Economics",
    expertise: ["Economics", "Finance"],
    charge: "₹1700/hour",
    location: "Chandigarh, Punjab",
    image: "https://randomuser.me/api/portraits/men/23.jpg",
  },
];

export const courses = [
  {
    id: 1,
    name: "React for Beginners",
    price: 99.99,
    teacherName: "John Doe",
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c",
    location: "New York, USA",
    rating: 4.5,
  },
  {
    id: 2,
    name: "Advanced JavaScript",
    price: 149.99,
    teacherName: "Jane Smith",
    image: "https://images.unsplash.com/photo-1524985069026-dd778a71c7b4",
    location: "San Francisco, USA",
    rating: 4.7,
  },
  {
    id: 3,
    name: "Python for Data Science",
    price: 199.99,
    teacherName: "Robert Brown",
    image: "https://images.unsplash.com/photo-1529059997568-a71c55d3b3d7",
    location: "Chicago, USA",
    rating: 4.8,
  },
  {
    id: 4,
    name: "Introduction to Machine Learning",
    price: 129.99,
    teacherName: "Alice Johnson",
    image: "https://images.unsplash.com/photo-1512820790803-83ca734da794",
    location: "Los Angeles, USA",
    rating: 4.6,
  },
  {
    id: 5,
    name: "Web Development Bootcamp",
    price: 249.99,
    teacherName: "Michael Lee",
    image: "https://images.unsplash.com/photo-1516910817563-4df8e4a9e3a9",
    location: "Seattle, USA",
    rating: 4.9,
  },
  {
    id: 6,
    name: "Data Structures and Algorithms",
    price: 179.99,
    teacherName: "Karen Davis",
    image: "https://images.unsplash.com/photo-1532012197267-da84d127e765",
    location: "Boston, USA",
    rating: 4.8,
  },
  {
    id: 7,
    name: "UI/UX Design Principles",
    price: 139.99,
    teacherName: "Chris Wilson",
    image: "https://images.unsplash.com/photo-1544717308-8b5313e03b7f",
    location: "Austin, USA",
    rating: 4.7,
  },
  {
    id: 8,
    name: "DevOps Essentials",
    price: 189.99,
    teacherName: "Patricia Moore",
    image: "https://images.unsplash.com/photo-1554475901-4538ddfbccc1",
    location: "Denver, USA",
    rating: 4.6,
  },
  {
    id: 9,
    name: "Cybersecurity Basics",
    price: 159.99,
    teacherName: "James Taylor",
    image: "https://images.unsplash.com/photo-1537498425277-c283d32ef9db",
    location: "Houston, USA",
    rating: 4.5,
  },
  {
    id: 10,
    name: "Cloud Computing with AWS",
    price: 199.99,
    teacherName: "Mary Anderson",
    image: "https://images.unsplash.com/photo-1555685812-4b7433adb21e",
    location: "Phoenix, USA",
    rating: 4.8,
  },
  {
    id: 11,
    name: "Mobile App Development with React Native",
    price: 149.99,
    teacherName: "David Thomas",
    image: "https://images.unsplash.com/photo-1533227268428-e9ff28b662c3",
    location: "Philadelphia, USA",
    rating: 4.7,
  },
  {
    id: 12,
    name: "Big Data Analytics",
    price: 219.99,
    teacherName: "Linda Martinez",
    image: "https://images.unsplash.com/photo-1528440636851-85c5ad4b3fae",
    location: "Dallas, USA",
    rating: 4.8,
  },
  {
    id: 13,
    name: "Blockchain for Beginners",
    price: 129.99,
    teacherName: "Charles White",
    image: "https://images.unsplash.com/photo-1499364615650-ec38552f4f34",
    location: "San Diego, USA",
    rating: 4.5,
  },
  {
    id: 14,
    name: "Artificial Intelligence Fundamentals",
    price: 179.99,
    teacherName: "Barbara Harris",
    image: "https://images.unsplash.com/photo-1554118811-1e2d5dc760cc",
    location: "Miami, USA",
    rating: 4.7,
  },
  {
    id: 15,
    name: "PHP for Web Development",
    price: 99.99,
    teacherName: "Joseph Clark",
    image: "https://images.unsplash.com/photo-1517487881594-2787fef5ebf7",
    location: "Atlanta, USA",
    rating: 4.6,
  },
  {
    id: 16,
    name: "SQL and Database Management",
    price: 119.99,
    teacherName: "Susan Lewis",
    image: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f",
    location: "Portland, USA",
    rating: 4.7,
  },
  {
    id: 17,
    name: "Ruby on Rails",
    price: 139.99,
    teacherName: "Paul Walker",
    image: "https://images.unsplash.com/photo-1505685296765-3a2736de412f",
    location: "Las Vegas, USA",
    rating: 4.6,
  },
  {
    id: 18,
    name: "C++ Programming",
    price: 109.99,
    teacherName: "Nancy Hall",
    image: "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f",
    location: "Detroit, USA",
    rating: 4.5,
  },
  {
    id: 19,
    name: "Swift for iOS Development",
    price: 179.99,
    teacherName: "Daniel Young",
    image: "https://images.unsplash.com/photo-1525088553748-988f4278a850",
    location: "San Jose, USA",
    rating: 4.7,
  },
  {
    id: 20,
    name: "Go Programming Language",
    price: 149.99,
    teacherName: "Laura King",
    image: "https://images.unsplash.com/photo-1529148482759-b35b25c1337e",
    location: "Charlotte, USA",
    rating: 4.8,
  },
  {
    id: 21,
    name: "Kotlin for Android Development",
    price: 129.99,
    teacherName: "Steven Allen",
    image: "https://images.unsplash.com/photo-1544717308-8b5313e03b7f",
    location: "Indianapolis, USA",
    rating: 4.7,
  },
  {
    id: 22,
    name: "R Programming for Statistics",
    price: 139.99,
    teacherName: "Lisa Scott",
    image: "https://images.unsplash.com/photo-1529042410759-befb1204b468",
    location: "Jacksonville, USA",
    rating: 4.6,
  },
  {
    id: 23,
    name: "Ethical Hacking",
    price: 199.99,
    teacherName: "Brian Hill",
    image: "https://images.unsplash.com/photo-1516979187457-637abb4f9353",
    location: "Columbus, USA",
    rating: 4.8,
  },
  {
    id: 24,
    name: "Game Development with Unity",
    price: 169.99,
    teacherName: "Karen Green",
    image: "https://images.unsplash.com/photo-1516979187457-637abb4f9353",
    location: "Fort Worth, USA",
    rating: 4.9,
  },
  {
    id: 25,
    name: "Augmented Reality with ARKit",
    price: 189.99,
    teacherName: "Edward Adams",
    image: "https://images.unsplash.com/photo-1554475901-4538",
  },
];

export const liveTeacherData = [
  {
    id: 1,
    instructor: "Tanvi",
    className: "French Language Classes",
    date: "Sat, 27 Jul at 02:00pm IST",
    reviews: 23,
    rating: 5,

    imageUrl: "https://via.placeholder.com/150",
    isLive: true,
    classStartTime: "00:24:38",
    isFree: true,
  },
  {
    id: 2,
    instructor: "John Doe",
    className: "Spanish Language Classes",
    date: "Sun, 28 Jul at 03:00pm IST",
    reviews: 15,
    rating: 4.5,
    imageUrl: "https://via.placeholder.com/150",
    isLive: true,
    classStartTime: "00:45:21",
    isFree: true,
  },
  {
    id: 3,
    instructor: "Jane Smith",
    className: "German Language Classes",
    date: "Mon, 29 Jul at 04:00pm IST",
    reviews: 30,
    rating: 4.8,
    imageUrl: "https://via.placeholder.com/150",
    isLive: true,
    classStartTime: "01:15:30",
    isFree: true,
  },
  {
    id: 4,
    instructor: "Alice Johnson",
    className: "Italian Language Classes",
    date: "Tue, 30 Jul at 05:00pm IST",
    reviews: 10,
    rating: 4.2,
    imageUrl: "https://via.placeholder.com/150",
    isLive: true,
    classStartTime: "00:55:12",
    isFree: true,
  },
  {
    id: 5,
    instructor: "Bob Brown",
    className: "Japanese Language Classes",
    date: "Wed, 31 Jul at 06:00pm IST",
    reviews: 20,
    rating: 4.9,
    imageUrl: "https://via.placeholder.com/150",
    isLive: true,
    classStartTime: "01:35:45",
    isFree: true,
  },
  {
    id: 6,
    instructor: "Charlie Davis",
    className: "Chinese Language Classes",
    date: "Thu, 1 Aug at 07:00pm IST",
    reviews: 18,
    rating: 4.7,
    imageUrl: "https://via.placeholder.com/150",
    isLive: true,
    classStartTime: "01:25:37",
    isFree: true,
  },
  {
    id: 7,
    instructor: "Diana Evans",
    className: "Korean Language Classes",
    date: "Fri, 2 Aug at 08:00pm IST",
    reviews: 25,
    rating: 4.6,
    imageUrl: "https://via.placeholder.com/150",
    isLive: true,
    classStartTime: "00:50:28",
    isFree: true,
  },
  {
    id: 8,
    instructor: "Ethan Foster",
    className: "Russian Language Classes",
    date: "Sat, 3 Aug at 09:00pm IST",
    reviews: 22,
    rating: 4.4,
    imageUrl: "https://via.placeholder.com/150",
    isLive: true,
    classStartTime: "01:10:15",
    isFree: true,
  },
  {
    id: 9,
    instructor: "Fiona Green",
    className: "Portuguese Language Classes",
    date: "Sun, 4 Aug at 10:00pm IST",
    reviews: 12,
    rating: 4.3,
    imageUrl: "https://via.placeholder.com/150",
    isLive: true,
    classStartTime: "00:30:55",
    isFree: true,
  },
  {
    id: 10,
    instructor: "George Harris",
    className: "Arabic Language Classes",
    date: "Mon, 5 Aug at 11:00pm IST",
    reviews: 17,
    rating: 4.8,
    imageUrl: "https://via.placeholder.com/150",
    isLive: true,
    classStartTime: "01:05:22",
    isFree: true,
  },
  {
    id: 11,
    instructor: "Hannah Jackson",
    className: "Hindi Language Classes",
    date: "Tue, 6 Aug at 12:00pm IST",
    reviews: 20,
    rating: 4.9,
    imageUrl: "https://via.placeholder.com/150",
    isLive: true,
    classStartTime: "00:35:40",
    isFree: true,
  },
  {
    id: 12,
    instructor: "Ian King",
    className: "Swedish Language Classes",
    date: "Wed, 7 Aug at 01:00pm IST",
    reviews: 18,
    rating: 4.6,
    imageUrl: "https://via.placeholder.com/150",
    isLive: true,
    classStartTime: "01:20:55",
    isFree: true,
  },
  {
    id: 13,
    instructor: "Jasmine Lee",
    className: "Dutch Language Classes",
    date: "Thu, 8 Aug at 02:00pm IST",
    reviews: 24,
    rating: 4.7,
    imageUrl: "https://via.placeholder.com/150",
    isLive: true,
    classStartTime: "00:40:30",
    isFree: true,
  },
  {
    id: 14,
    instructor: "Kyle Moore",
    className: "Greek Language Classes",
    date: "Fri, 9 Aug at 03:00pm IST",
    reviews: 14,
    rating: 4.4,
    imageUrl: "https://via.placeholder.com/150",
    isLive: true,
    classStartTime: "00:50:45",
    isFree: true,
  },
  {
    id: 15,
    instructor: "Laura Nguyen",
    className: "Hebrew Language Classes",
    date: "Sat, 10 Aug at 04:00pm IST",
    reviews: 19,
    rating: 4.8,
    imageUrl: "https://via.placeholder.com/150",
    isLive: true,
    classStartTime: "01:05:10",
    isFree: true,
  },
  {
    id: 16,
    instructor: "Mike Ortiz",
    className: "Turkish Language Classes",
    date: "Sun, 11 Aug at 05:00pm IST",
    reviews: 21,
    rating: 4.5,
    imageUrl: "https://via.placeholder.com/150",
    isLive: true,
    classStartTime: "01:25:32",
    isFree: true,
  },
  {
    id: 17,
    instructor: "Nina Perez",
    className: "Persian Language Classes",
    date: "Mon, 12 Aug at 06:00pm IST",
    reviews: 13,
    rating: 4.3,
    imageUrl: "https://via.placeholder.com/150",
    isLive: true,
    classStartTime: "00:45:21",
    isFree: true,
  },
  {
    id: 18,
    instructor: "Oscar Quinn",
    className: "Thai Language Classes",
    date: "Tue, 13 Aug at 07:00pm IST",
    reviews: 16,
    rating: 4.5,
    imageUrl: "https://via.placeholder.com/150",
    isLive: true,
    classStartTime: "01",
  },
];
