export const teachersData = [
  {
    id: 1,
    name: "Rajesh Kumar",
    age: 30,
    education: "Masters in Mathematics",
    expertise: ["Mathematics", "Statistics"],
    charge: "₹1500/hour",
    location: "Mumbai, Maharashtra",
    image: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    id: 2,
    name: "Anjali Singh",
    age: 32,
    education: "Bachelor of Science in Physics",
    expertise: ["Physics", "Chemistry"],
    charge: "₹1200/hour",
    location: "New Delhi, Delhi",
    image: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    id: 3,
    name: "Amit Sharma",
    age: 35,
    education: "Ph.D. in History",
    expertise: ["History", "Political Science"],
    charge: "₹1800/hour",
    location: "Bangalore, Karnataka",
    image: "https://randomuser.me/api/portraits/men/3.jpg",
  },
  {
    id: 4,
    name: "Priya Patel",
    age: 28,
    education: "Bachelor of Arts in English Literature",
    expertise: ["English Literature", "Language Arts"],
    charge: "₹1000/hour",
    location: "Ahmedabad, Gujarat",
    image: "https://randomuser.me/api/portraits/women/4.jpg",
  },
  {
    id: 5,
    name: "Sandeep Singh",
    age: 31,
    education: "Masters in Computer Science",
    expertise: ["Computer Science", "Programming"],
    charge: "₹1600/hour",
    location: "Pune, Maharashtra",
    image: "https://randomuser.me/api/portraits/men/5.jpg",
  },
  {
    id: 6,
    name: "Deepika Reddy",
    age: 29,
    education: "Bachelor of Science in Biology",
    expertise: ["Biology", "Environmental Science"],
    charge: "₹1100/hour",
    location: "Hyderabad, Telangana",
    image: "https://randomuser.me/api/portraits/women/6.jpg",
  },
  {
    id: 7,
    name: "Vivek Verma",
    age: 34,
    education: "Ph.D. in Economics",
    expertise: ["Economics", "Business Studies"],
    charge: "₹1900/hour",
    location: "Chennai, Tamil Nadu",
    image: "https://randomuser.me/api/portraits/men/7.jpg",
  },
  {
    id: 8,
    name: "Neha Gupta",
    age: 27,
    education: "Bachelor of Arts in Psychology",
    expertise: ["Psychology", "Sociology"],
    charge: "₹1300/hour",
    location: "Jaipur, Rajasthan",
    image: "https://randomuser.me/api/portraits/women/8.jpg",
  },
  {
    id: 9,
    name: "Rahul Kumar",
    age: 33,
    education: "Masters in Chemistry",
    expertise: ["Chemistry", "Organic Chemistry"],
    charge: "₹1700/hour",
    location: "Kolkata, West Bengal",
    image: "https://randomuser.me/api/portraits/men/9.jpg",
  },
  {
    id: 10,
    name: "Pooja Sharma",
    age: 26,
    education: "Bachelor of Education",
    expertise: ["Primary Education", "Early Childhood Development"],
    charge: "₹900/hour",
    location: "Lucknow, Uttar Pradesh",
    image: "https://randomuser.me/api/portraits/women/10.jpg",
  },
  {
    id: 11,
    name: "Sanjay Singh",
    age: 36,
    education: "Ph.D. in Physics",
    expertise: ["Physics", "Astrophysics"],
    charge: "₹2000/hour",
    location: "Bengaluru, Karnataka",
    image: "https://randomuser.me/api/portraits/men/11.jpg",
  },
  {
    id: 12,
    name: "Meera Desai",
    age: 30,
    education: "Masters in Arts",
    expertise: ["History", "Geography"],
    charge: "₹1400/hour",
    location: "Ahmedabad, Gujarat",
    image: "https://randomuser.me/api/portraits/women/12.jpg",
  },
  {
    id: 13,
    name: "Gaurav Kapoor",
    age: 29,
    education: "Bachelor of Technology in Mechanical Engineering",
    expertise: ["Mechanical Engineering", "Thermodynamics"],
    charge: "₹1500/hour",
    location: "Chandigarh, Punjab",
    image: "https://randomuser.me/api/portraits/men/13.jpg",
  },
  {
    id: 14,
    name: "Shikha Reddy",
    age: 32,
    education: "Masters in Fine Arts",
    expertise: ["Fine Arts", "Painting"],
    charge: "₹1200/hour",
    location: "Hyderabad, Telangana",
    image: "https://randomuser.me/api/portraits/women/14.jpg",
  },
  {
    id: 15,
    name: "Alok Sharma",
    age: 33,
    education: "Ph.D. in Mathematics",
    expertise: ["Mathematics", "Algebra"],
    charge: "₹1800/hour",
    location: "Pune, Maharashtra",
    image: "https://randomuser.me/api/portraits/men/15.jpg",
  },
  {
    id: 16,
    name: "Nisha Patel",
    age: 31,
    education: "Bachelor of Science in Biology",
    expertise: ["Biology", "Anatomy"],
    charge: "₹1300/hour",
    location: "Ahmedabad, Gujarat",
    image: "https://randomuser.me/api/portraits/women/16.jpg",
  },
  {
    id: 17,
    name: "Rajesh Verma",
    age: 34,
    education: "Masters in English Literature",
    expertise: ["English Literature", "Language Arts"],
    charge: "₹1600/hour",
    location: "Kolkata, West Bengal",
    image: "https://randomuser.me/api/portraits/men/17.jpg",
  },
  {
    id: 18,
    name: "Sneha Kapoor",
    age: 27,
    education: "Bachelor of Arts in Sociology",
    expertise: ["Sociology", "Social Work"],
    charge: "₹1100/hour",
    location: "Chennai, Tamil Nadu",
    image: "https://randomuser.me/api/portraits/women/18.jpg",
  },
  {
    id: 19,
    name: "Prashant Mishra",
    age: 35,
    education: "Ph.D. in History",
    expertise: ["History", "Political Science"],
    charge: "₹1900/hour",
    location: "Bengaluru, Karnataka",
    image: "https://randomuser.me/api/portraits/men/19.jpg",
  },
  {
    id: 20,
    name: "Shruti Sharma",
    age: 28,
    education: "Bachelor of Science in Chemistry",
    expertise: ["Chemistry", "Organic Chemistry"],
    charge: "₹1400/hour",
    location: "New Delhi, Delhi",
    image: "https://randomuser.me/api/portraits/women/20.jpg",
  },
  {
    id: 21,
    name: "Rahul Khanna",
    age: 29,
    education: "Masters in Business Administration",
    expertise: ["Business Studies", "Marketing"],
    charge: "₹1500/hour",
    location: "Mumbai, Maharashtra",
    image: "https://randomuser.me/api/portraits/men/21.jpg",
  },
  {
    id: 22,
    name: "Kavita Gupta",
    age: 30,
    education: "Bachelor of Arts in Psychology",
    expertise: ["Psychology", "Counseling"],
    charge: "₹1200/hour",
    location: "Jaipur, Rajasthan",
    image: "https://randomuser.me/api/portraits/women/22.jpg",
  },
  {
    id: 23,
    name: "Vikram Singh",
    age: 32,
    education: "Masters in Economics",
    expertise: ["Economics", "Finance"],
    charge: "₹1700/hour",
    location: "Chandigarh, Punjab",
    image: "https://randomuser.me/api/portraits/men/23.jpg",
  },
];
